language: generic
sudo: false
notifications:
  email: false

branches:  # blacklist
  except:
    - docs

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TEST_ENV=defaults
    - python: 3.6
      env: TEST_ENV=flake8

before_install:
  - wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
  - ./bin/micromamba shell init -s bash -p ~/micromamba
  - source ~/.bashrc

install:
  - micromamba activate
  - micromamba install python=3.8 flake8 -c conda-forge
  - pip install coveralls
  - pip install -e .

script:
  - if [[ "$TEST_ENV" == "flake8" ]]; then
      flake8 -j auto rgitools;
    else
      pytest rgitools --verbose --cov=rgitools --cov-report term-missing;
    fi

after_success:
  - coveralls
