language: python
sudo: false
notifications:
email: false

branches:  # blacklist
  except:
    - docs

matrix:
  fast_finish: true
  include:
    - python: 3.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install pyyaml

install:
  - conda env create --file ci/requirements.yml --quiet
  - source activate test_env
  - pip install -e .

script:
  - pytest rgitools

after_success:
