name: rgitoolsdocs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy<1.17
  - scipy
  - shapely
  - matplotlib=3.0.3
  - Pillow
  - netcdf4
  - scikit-image
  - pyproj
  - cartopy
  - rasterio
  - ipython
  - sphinx
  - pip
  - pip:
    - bottleneck
    - numpydoc
    - descartes
    - pandas
    - xarray
    - geopandas
    - configobj
    - joblib
    - progressbar2
    - motionless
    - git+https://github.com/fmaussion/salem.git
    - git+https://github.com/OGGM/pytest-mpl
    - git+https://github.com/OGGM/oggm.git
